[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "serverless-http",
    "pg",
    "bcrypt",
    "jsonwebtoken",
    "dotenv",
    "sasl"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true